[package]
name = "comdirect-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = "0.12.19"
serde = { version = "1.0.219", features = ["derive"] }
uuid = { version = "1.17.0", features = ["v4"] }
serde_json = "1.0.140"
utils = { path = "../utils" }
tokio = "1.45.1"