//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "categories")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i32,
    pub category: Option<String>,
    pub subcategory: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::transaction_categories::Entity")]
    TransactionCategories,
}

impl Related<super::transaction_categories::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TransactionCategories.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
