//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "goal")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub owner_user_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub goal_type: String,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))")]
    pub amount: Decimal,
    #[sea_orm(column_type = "Text")]
    pub currency: String,
    pub scope_category_slugs: Vec<String>,
    pub scope_tags: Vec<String>,
    #[sea_orm(column_type = "Text")]
    pub scope_combine: String,
    #[sea_orm(column_type = "Text")]
    pub scope_tag_combine: String,
    #[sea_orm(column_type = "Text")]
    pub period_kind: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub period_cadence: Option<String>,
    pub period_start: Option<Date>,
    pub period_end: Option<Date>,
    pub archived: bool,
    pub revision: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
