//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "llm_label_cache")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub fingerprint: String,
    pub category_id: Option<Uuid>,
    #[sea_orm(column_type = "Text", nullable)]
    pub proposed_path: Option<String>,
    #[sea_orm(column_type = "Decimal(Some((4, 3)))")]
    pub confidence: Decimal,
    #[sea_orm(column_type = "Text")]
    pub provider: String,
    #[sea_orm(column_type = "Text")]
    pub model: String,
    #[sea_orm(column_type = "Text")]
    pub prompt_version: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub reasoning: Option<String>,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
