//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

pub mod prelude;

pub mod account;
pub mod account_balance;
pub mod app_user;
pub mod category;
pub mod display_alias;
pub mod goal;
pub mod learning_exemption;
pub mod legacy_account;
pub mod legacy_account_balance;
pub mod legacy_account_transactions;
pub mod llm_label_cache;
pub mod projection_offset;
pub mod rule;
pub mod transaction;
pub mod transaction_insight;
pub mod transaction_label;
pub mod transaction_split;
pub mod transaction_tag;
pub mod transaction_user_label;
pub mod user_account;
pub mod user_session;
