//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

pub mod prelude;

pub mod account;
pub mod account_balance;
pub mod categories;
pub mod mandate_categories;
pub mod transaction_categories;
pub mod transactions;
