//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "rule")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    pub category_id: Uuid,
    #[sea_orm(column_type = "JsonBinary")]
    pub conditions: Json,
    pub priority: i32,
    #[sea_orm(column_type = "Text")]
    pub state: String,
    #[sea_orm(column_type = "Text")]
    pub origin: String,
    pub auto_approved: bool,
    pub user_touched: bool,
    #[sea_orm(column_type = "Decimal(Some((4, 3)))", nullable)]
    pub confidence: Option<Decimal>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub evidence: Option<Json>,
    pub created_at: DateTimeWithTimeZone,
    pub revision: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
