//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "transactions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub reference: String,
    pub account_id: Option<String>,
    pub booking_status: String,
    pub booking_date: String,
    #[sea_orm(column_type = "Double")]
    pub amount: f64,
    pub remitter: Option<String>,
    pub deptor: Option<String>,
    pub creditor: Option<String>,
    pub creditor_id: Option<String>,
    pub creditor_mandate_id: Option<String>,
    pub remittance_info: String,
    pub transaction_type: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_one = "super::transaction_categories::Entity")]
    TransactionCategories,
}

impl Related<super::transaction_categories::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TransactionCategories.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
