//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "transaction_label")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub transaction_id: Uuid,
    pub category_id: Option<Uuid>,
    #[sea_orm(column_type = "Text")]
    pub label_source: String,
    pub rule_id: Option<Uuid>,
    #[sea_orm(column_type = "Decimal(Some((4, 3)))", nullable)]
    pub confidence: Option<Decimal>,
    #[sea_orm(column_type = "Text")]
    pub status: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub review_reason: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub proposed_category_path: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub provider: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub model: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub prompt_version: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub fingerprint: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub reasoning: Option<String>,
    pub labeled_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
