//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "transaction_insight")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub transaction_id: Uuid,
    pub is_transfer: bool,
    pub transfer_counterpart_id: Option<Uuid>,
    #[sea_orm(column_type = "Text", nullable)]
    pub transfer_match: Option<String>,
    pub is_recurring: bool,
    pub recurring_series_id: Option<Uuid>,
    #[sea_orm(column_type = "Text", nullable)]
    pub recurring_cadence: Option<String>,
    #[sea_orm(column_type = "Decimal(Some((20, 4)))", nullable)]
    pub recurring_median_amount: Option<Decimal>,
    pub detected_at: DateTimeWithTimeZone,
    pub revision: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
